name: infra-whatsapp-n8n
services:
  postgres:
    container_name: postgres
    image: postgres:15
    command:
      ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  evolution_api:
    container_name: evolution_api
    # image: atendai/evolution-api:latest
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./evolution_instances:/evolution/instances
    environment:
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - CACHE_REDIS_ENABLED=false
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      # - CONFIG_SESSION_PHONE_VERSION=2.3000.1030721699

  n8n:
    container_name: n8n
    build: .
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - GENERIC_TIMEZONE=America/Sao_Paulo      
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./local-files:/files
  
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis_data:/data

volumes:
  n8n_data:
  evolution_instances:
  postgres_data:
  redis_data:
